# nixpack.toml

# Explicitly tell Nixpacks this is a Node.js app
[provider]
name = "node"

# -----------------------
# Setup Node.js & NPM
# -----------------------
[phases.setup]
nixPkgs = ["nodejs", "npm"]

# -----------------------
# Backend Setup
# -----------------------
[phases.backend]
dir = "Backend"
install = "npm install --production"
build = "echo 'Backend build skipped'"

# -----------------------
# Frontend Build
# -----------------------
[phases.frontend]
dir = "Frontend"
install = "npm install"
build = "npm run build"
postBuild = "cp -r build ../Backend/public"

# -----------------------
# Start Phase
# -----------------------
[start]
cmd = "cd Backend && npm start"

# -----------------------
# Environment
# -----------------------
[env]
PORT = "5000"
NODE_ENV = "production"
