# Tell Nixpacks this is a Node.js app
[provider]
name = "node"

# -----------------------
# Setup Node.js & NPM
# -----------------------
[phases.setup]
nixPkgs = ["nodejs", "npm"]

# -----------------------
# Install Phase
# -----------------------
[phases.install]
# Install backend first
command = "cd Backend && npm install && cd ../Frontend && npm install"

# -----------------------
# Build Phase
# -----------------------
[phases.build]
command = """
cd Frontend && npm run build && \
cp -r build ../Backend/public
"""

# -----------------------
# Start Phase
# -----------------------
[start]
cmd = "cd Backend && npm start"

# -----------------------
# Environment
# -----------------------
[env]
PORT = "5000"
NODE_ENV = "production"
