[phases.setup]
commands = ["npm install"]

[phases.build]
commands = ["echo 'No build required for backend'"]

[phases.start]
commands = ["node server.js"]

[env]
NODE_ENV = "production"
PORT = "5000"
